### ISSUE TITLE
installation: should pywebpack v1.0.3 be pinned here?

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-assets#117]
Left-over from #113

**Comment by ntarocco** [comment]
From Alex:
>Theoretically if we follow the "coordinator" modules paradigm we shouldn't, i.e. tests will get the latest since it's a dependency of Flask-WebpackExt. The fact that users of invenio-assets have to upgrade their dependencies is though another issue which can e.g. be addressed in the cookiecutter

It is true that pip will install the latest, so it should be ok, unless someone installs a version before and then the theming will not work. We can probably close this. @slint?
