### ISSUE TITLE
webpack: update package.json dependencies

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-assets#118]
> I think we should upgrade dependencies too (run npm outdated). In particular there is an issue that Karolina encountered with Node 13, node-sass really depends on some Node versions, see here.
>
> With Node 13, node-sass should be at least 4.13.
>
> Maybe we should add a Travis matrix with different Node versions, from LTS (12) to 14?

Left over from #113

See [supported Node.js versions compatibility matrix](https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support)

**Comment by ParthS007** [comment]
<img width="548" alt="Screenshot 2020-08-24 at 13 38 01" src="https://user-images.githubusercontent.com/24358501/91040827-2d78a280-e60f-11ea-91cd-2e34c5adf2b3.png">
