### ISSUE TITLE
Review chunking of assets

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-assets#121]
From conversation on Discord, seems like the homepage is including vendors for `d3`, but the content of the JS file is the `jQuery` library (detected by @ntarocco).

![My_site](https://user-images.githubusercontent.com/1698163/82052836-92da0080-96bc-11ea-8409-23bdb6e643cd.png)

**Comment by jrcastro2** [comment]
Just checked this and seems to not be included anymore
![image](https://user-images.githubusercontent.com/15194802/91050313-c367f980-e61e-11ea-9233-4a8073c4233f.png)
