### ISSUE TITLE
webpack prefixing of themes

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-assets#124]
Because of this join: https://github.com/inveniosoftware/invenio-assets/blob/master/invenio_assets/webpack.py#L50

Every theme has to be in their names folder. However, in many modules:

- `invenio-theme`
- `invenio-i18n`
- (maybe more)

The bootstrap assets are in the root:

```
js/...
scss/...
semantic-ui/
```

For backwards compatibility reasons this should be addressed. Some possible solutions could be:
1. Fallback:
``` python
        self.default = default
        self.themes = {}
        for theme, bundle in themes.items():
            path = os.path.join(folder, theme) if theme != self.default else folder
            self.themes[theme] = WebpackBundle(
                import_name,
                path
                **bundle
            )
```

2. Change the folder tree in the affected modules.

However, as it is now bootstrap three cannot be used. It will either load the application files or invenio ones, but never both.

**Comment by lnielsen** [comment]
This problem is related to being able to properly upgrade from v3.3 to v3.4. See inveniosoftware/cookiecutter-invenio-instance#225.

**Comment by ppanero** [comment]
- invenio-theme ✅ 
-
