### ISSUE TITLE
webpack: establish convention for aliases naming

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-assets#132]
## Is your feature request related to a problem? Please describe.

When wanting to create an alias for JS/CSS assets provided, a name has to be decided on.

## Describe the solution you'd like

e.g. when making an alias for `invenio-search-ui` JS assets, one can go with either:

- `@js/invenio_search_ui` (actually looks like what's in `assets/`)
- `@invenio_search_ui/js`
- `@invenio_search_ui`

**Comment by lnielsen** [comment]
After IRL discussing: Going with ``@js/invenio_search_ui``

**Comment by slint** [comment]
The only module at the moment that doesn't follow the convention is invenio-theme https://github.com/inveniosoftware/invenio-theme/issues/200, thus I'm closing the issue
