### ISSUE TITLE
Use Zopfli to optimize bandwidth ?

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio-assets#19]
Moved from https://github.com/inspirehep/inspire-next/issues/680

Read the following blog post:

http://blog.codinghorror.com/zopfli-optimization-literally-free-bandwidth/

And Zopfli seems like an interesting and 'not difficult' to implement improvement that could make our assets: plots, images, JS files much more efficient.

See comparison of jQuery library before/after compression:

https://mathiasbynens.be/demo/jquery-size

This is the library itself (written in C):

https://github.com/google/zopfli

This can be plugged in to different places: asset compilation, ingestion from arXiv (for plots) and so on.

**Comment by jirikuncar** [comment]
@jmartinm did you have time to perform any experiment? I found two Python projects that both seems almost dead.

- https://github.com/wnyc/py-zopfli
- https://pypi.python.org/pypi/zopfli

Please add more details on libraries and architecture or close it if there is no more interest in implementing it.

**Comment by jmartinm** [comment]
Thanks for checking the libraries. I will close for the moment as I am not sure when we will have time to look at it.
