### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-assets#27]
- check existing API functionality
- add missing important API functionality
- check API function signatures and parameters
- enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- plug API functions to existing docs

**Comment by tiborsimko** [comment]
Probably closed by #26.

**Comment by jirikuncar** [comment]
> enhance API docstrings (param, returns, raises, versionadded)

@tiborsimko it isn't done yet

**Comment by tiborsimko** [comment]
OK, although the `b1` release should really have come only afterwards... 

Let's keep on using `addresses #` for easier tracking.
