### ISSUE TITLE
SCSS files not compiling with webassets >=0.12

### ISSUE THREAD

**Issue by andrewm89** [inveniosoftware/invenio-assets#41]
There is a problem using relative paths with the import tag in scss files following the version release 0.12 of webassets.  With this being the minimum version currently in this module, the latest  release is not useable for us at the moment.

**Comment by jacquerie** [comment]
Same problem for us. I thought #38 was going to solve this...

**Comment by jirikuncar** [comment]
@andrewm89 can you provide a test case or traceback?

**Comment by andrewm89** [comment]
@jirikuncar Here's the stack trace we have:
'''
Failed, error was: scss: subprocess returned a non-success result code: 1, stdout=b'', stderr=b'{\n  "formatted": "Error: File to import not found or unreadable: variables\\n       Parent style sheet: stdin\\n        on line 23 of stdin\\n>> @import \\"variables\\";\\n   ^\\n",\n  "message": "File to import not found or unreadable: variables\\nParent style sheet: stdin",\n  "column": 1,\n  "line": 23,\n  "file": "stdin",\n  "status": 1\n}\n'
Building bundle: gen/tind_theme.%(version)s.css
'''

**Comment by jirikuncar** [comment]
@andrewm89 @jacquerie please try to use `node-scss` filter instead of `scss`.

**Comment by andrewm89** [comment]
@jirikuncar seems to work!  Will keep testing it until it breaks.

**Comment by jacquerie** [comment]
Yes, this fixes the issue on our side as well. Thanks!
