### ISSUE TITLE
global: avoid global Node.js binaries

### ISSUE THREAD

**Issue by slint** [inveniosoftware/invenio-assets#75]
Depending on your bundles configuration, in order to run `invenio assets build`, having specific binaries (eg. `node-sass`, `r.js` from `require.js`, `clean-css`, etc) installed globally is now a pre-requisite, and usually a separate step of the Invenio instance setup process (eg. running some `setup-npm.sh`).

Since it would be a lot of trouble (if not impossible) to convert the current asset building bundles to be executed using `npm run <some-build-script>`, probably the easiest way would be to have these build/dev dependencies installed in `node_modules` and inject the `static/node_modules/.bin` folder to the PATH before executing the `invenio assets build` command.

**Bonus Round**
Detecting the required binaries is possible by scanning the `Bundle.filters` property, so automatically generating some `devDependencies` could be possible as well. Minimum/maximum versions for these binaries should be taken into account though.

**Comment by lnielsen** [comment]
As we're moving towards webpack this might be fixed properly there?

**Comment by slint** [comment]
Since Webpack (ie. `flask-webpackext`) is definitely a step towards boiling down asset building to a single `invenio assets build` command with minimal requirements (technically only a compatible version of `node`/`npm`), I guess yes :tada:

**Comment by lnielsen** [comment]
Closing as Webpack is now fully released.
